version: 2
updates:
  - package-ecosystem: pip
    directory: "/loadtest"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python
  - package-ecosystem: pip
    directory: "/selenium"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - python
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
